[package]
name = "rust-fw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
netfilter_queue = { path = "../netfilter_queue" }
libc = "^0.2"